name: Run N5_model_dev Notebook

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install jupyter nbconvert

      - name: Run N5_model_dev Notebook
        run: |
          jupyter nbconvert --to notebook --execute N5_Model_dev.ipynb --output executed_N5_Model_dev.ipynb

      - name: Upload executed notebook artifact
        uses: actions/upload-artifact@v4
        with:
          name: executed-notebook
          path: executed_N5_Model_dev.ipynb
