# name: Run Experiment Notebook

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install jupyter nbconvert

      - name: Run Experiment Notebook
        run: |
          jupyter nbconvert --to notebook --execute Fake-review-detection/Notebooks/N5_Modal_dev.ipynb --output executed_notebook.ipynb
      - name: Upload executed notebook as artifact
        uses: actions/upload-artifact@v3
        with:
          name: executed-notebook
          path: executed_notebook.ipynb
