name: Run N5_Modal_dev Notebook

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Display working directory
        run: pwd

      - name: List repository contents
        run: ls -R

      - name: Download Data Files
        run: |
          mkdir -p Data/Feature-Engineered
          # Replace the URLs below with the actual URLs where your CSV files are hosted
          wget -O Data/Feature-Engineered/preprocessed_lemmatization_features.csv https://example.com/path/to/preprocessed_lemmatization_features.csv
          wget -O Data/Feature-Engineered/preprocessed_no_stopwords_features.csv https://example.com/path/to/preprocessed_no_stopwords_features.csv
          wget -O Data/Feature-Engineered/preprocessed_no_stopwords_no_lemmatization_features.csv https://example.com/path/to/preprocessed_no_stopwords_no_lemmatization_features.csv
          wget -O Data/Feature-Engineered/preprocessed_stemming_features.csv https://example.com/path/to/preprocessed_stemming_features.csv
          wget -O Data/Feature-Engineered/preprocessed_stemming_no_stopwords_features.csv https://example.com/path/to/preprocessed_stemming_no_stopwords_features.csv

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install jupyter nbconvert tensorflow

      - name: Execute N5_Modal_dev Notebook
        run: jupyter nbconvert --to notebook --execute Notebooks/N5_Modal_dev.ipynb --output executed_N5_Modal_dev.ipynb

      - name: Upload executed notebook artifact
        uses: actions/upload-artifact@v4
        with:
          name: executed-notebook
          path: executed_N5_Modal_dev.ipynb
